development:
  adapter: mysql2
  database: juvia
  host: localhost
  username: root
  password: hipass

test:
  adapter: mysql2
  database: juvia
  host: localhost
  username: root
  password: hipass

production:
  adapter: mysql2
  database: juvia
  host: localhost
  username: root
  password: hipass
